//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYWE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XYWE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei
        ///Bisasam
        ///Bisaknosp
        ///Bisaflor
        ///Glumanda
        ///Glutexo
        ///Glurak
        ///Schiggy
        ///Schillok
        ///Turtok
        ///Raupy
        ///Safcon
        ///Smettbo
        ///Hornliu
        ///Kokuna
        ///Bibor
        ///Taubsi
        ///Tauboga
        ///Tauboss
        ///Rattfratz
        ///Rattikarl
        ///Habitak
        ///Ibitak
        ///Rettan
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandan
        ///Sandamer
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Piepi
        ///Pixi
        ///Vulpix
        ///Vulnona
        ///Pummeluff
        ///Knuddeluff
        ///Zubat
        ///Golbat
        ///Myrapla
        ///Duflor
        ///Giflor
        ///Paras
        ///Parasek
        ///Bluzuk
        ///Omot
        ///Digda
        ///Digdri
        ///Mauzi
        ///Snobilikat
        ///Enton
        ///Entoron
        ///Menki
        ///Rasaff
        ///Fukano
        ///Arkani
        ///Quapsel
        ///Quaputzi
        ///Quappo
        ///Abra
        ///Kadabra
        ///Simsala
        ///Machollo
        ///Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_de {
            get {
                return ResourceManager.GetString("text_Species_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///Pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_en {
            get {
                return ResourceManager.GetString("text_Species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huevo
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_es {
            get {
                return ResourceManager.GetString("text_Species_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Œuf
        ///Bulbizarre
        ///Herbizarre
        ///Florizarre
        ///Salamèche
        ///Reptincel
        ///Dracaufeu
        ///Carapuce
        ///Carabaffe
        ///Tortank
        ///Chenipan
        ///Chrysacier
        ///Papilusion
        ///Aspicot
        ///Coconfort
        ///Dardargnan
        ///Roucool
        ///Roucoups
        ///Roucarnage
        ///Rattata
        ///Rattatac
        ///Piafabec
        ///Rapasdepic
        ///Abo
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sabelette
        ///Sablaireau
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Mélofée
        ///Mélodelfe
        ///Goupix
        ///Feunard
        ///Rondoudou
        ///Grodoudou
        ///Nosferapti
        ///Nosferalto
        ///Mystherbe
        ///Ortide
        ///Rafflesia
        ///Paras
        ///Parasect
        ///Mimitoss
        ///Aéromite
        ///Taupiqueur
        ///Triopikeur
        ///Miaouss
        ///Persian
        ///Psykokwak
        ///Akwakwak
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_fr {
            get {
                return ResourceManager.GetString("text_Species_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uovo
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_it {
            get {
                return ResourceManager.GetString("text_Species_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タマゴ
        ///フシギダネ
        ///フシギソウ
        ///フシギバナ
        ///ヒトカゲ
        ///リザード
        ///リザードン
        ///ゼニガメ
        ///カメール
        ///カメックス
        ///キャタピー
        ///トランセル
        ///バタフリー
        ///ビードル
        ///コクーン
        ///スピアー
        ///ポッポ
        ///ピジョン
        ///ピジョット
        ///コラッタ
        ///ラッタ
        ///オニスズメ
        ///オニドリル
        ///アーボ
        ///アーボック
        ///ピカチュウ
        ///ライチュウ
        ///サンド
        ///サンドパン
        ///ニドラン♀
        ///ニドリーナ
        ///ニドクイン
        ///ニドラン♂
        ///ニドリーノ
        ///ニドキング
        ///ピッピ
        ///ピクシー
        ///ロコン
        ///キュウコン
        ///プリン
        ///プクリン
        ///ズバット
        ///ゴルバット
        ///ナゾノクサ
        ///クサイハナ
        ///ラフレシア
        ///パラス
        ///パラセクト
        ///コンパン
        ///モルフォン
        ///ディグダ
        ///ダグトリオ
        ///ニャース
        ///ペルシアン
        ///コダック
        ///ゴルダック
        ///マンキー
        ///オコリザル
        ///ガーディ
        ///ウインディ
        ///ニョロモ
        ///ニョロゾ
        ///ニョロボン
        ///ケーシィ
        ///ユンゲラー
        ///フーディン
        ///ワンリキー
        ///ゴーリキー
        ///カイリキー
        ///マダツボミ
        ///ウツドン
        ///ウツボット
        ///メノクラゲ
        ///ドククラゲ
        ///イシツブテ
        ///ゴローン
        ///ゴローニャ
        ///ポニータ
        ///ギャロップ
        ///ヤドン
        ///ヤドラン
        ///コイル
        ///レアコイル
        ///カモネギ
        ///ドードー
        ///ドードリオ
        ///パウワウ
        ///ジュゴン
        ///ベトベター
        ///ベトベトン
        ///シェルダー
        ///パルシェン
        ///ゴース
        ///ゴースト
        ///ゲン [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_ja {
            get {
                return ResourceManager.GetString("text_Species_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알
        ///이상해씨
        ///이상해풀
        ///이상해꽃
        ///파이리
        ///리자드
        ///리자몽
        ///꼬부기
        ///어니부기
        ///거북왕
        ///캐터피
        ///단데기
        ///버터플
        ///뿔충이
        ///딱충이
        ///독침붕
        ///구구
        ///피죤
        ///피죤투
        ///꼬렛
        ///레트라
        ///깨비참
        ///깨비드릴조
        ///아보
        ///아보크
        ///피카츄
        ///라이츄
        ///모래두지
        ///고지
        ///니드런♀
        ///니드리나
        ///니드퀸
        ///니드런♂
        ///니드리노
        ///니드킹
        ///삐삐
        ///픽시
        ///식스테일
        ///나인테일
        ///푸린
        ///푸크린
        ///주뱃
        ///골뱃
        ///뚜벅쵸
        ///냄새꼬
        ///라플레시아
        ///파라스
        ///파라섹트
        ///콘팡
        ///도나리
        ///디그다
        ///닥트리오
        ///나옹
        ///페르시온
        ///고라파덕
        ///골덕
        ///망키
        ///성원숭
        ///가디
        ///윈디
        ///발챙이
        ///슈륙챙이
        ///강챙이
        ///캐이시
        ///윤겔라
        ///후딘
        ///알통몬
        ///근육몬
        ///괴력몬
        ///모다피
        ///우츠동
        ///우츠보트
        ///왕눈해
        ///독파리
        ///꼬마돌
        ///데구리
        ///딱구리
        ///포니타
        ///날쌩마
        ///야돈
        ///야도란
        ///코일
        ///레어코일
        ///파오리
        ///두두
        ///두트리오
        ///쥬쥬
        ///쥬레곤
        ///질퍽이
        ///질뻐기
        ///셀러
        ///파르셀
        ///고오스
        ///고우스트
        ///팬텀
        ///롱스톤
        ///슬리프
        ///슬리퍼
        ///크랩
        ///킹크랩
        ///찌리리공
        ///붐볼
        ///아라리
        ///나시
        ///탕구리
        ///텅구리
        ///시라소몬
        ///홍수몬
        ///내루미
        ///또가스
        ///또도가스
        ///뿔카노
        ///코뿌리
        ///럭키
        ///덩쿠리
        ///캥카
        ///쏘드라
        ///시드라
        ///콘치
        ///왕콘치
        ///별가사리
        ///아쿠스타
        ///마임맨
        ///스라크
        ///루주라
        ///에레브
        ///마그마
        ///쁘사이저
        ///켄 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_ko {
            get {
                return ResourceManager.GetString("text_Species_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///Mysteriöser Ort
        ///
        ///Entfernter Ort
        ///
        ///Escissia
        ///
        ///Route 1
        ///Escissia-Pfad
        ///Aquarellia
        ///
        ///Route 2
        ///Progrès-Weg
        ///Nouvaria-Wald
        ///
        ///Route 3
        ///Ouvert-Weg
        ///Nouvaria City
        ///
        ///Route 4
        ///Parterre-Weg
        ///Illumina City
        ///
        ///Prismaturm
        ///
        ///Labor von Flordelis
        ///
        ///Route 5
        ///Coteau-Weg
        ///Vanitéa
        ///
        ///Château Tristesse
        ///
        ///Route 6
        ///Palais-Allee
        ///Magnum-Opus-Palast
        ///
        ///Route 7
        ///Rivière-Promenade
        ///Relievera City
        ///
        ///Route 8
        ///Muraille-Küstenpfad
        ///Petrophia
        ///
        ///Route 9
        ///Rihorn-Pass
        ///Kampfschloss
        ///
        ///Route 10
        ///Menhir-Weg
        ///Cromlexia
        ///
        ///Route 11
        ///Miroir-Weg
        ///Spiegelhöhle
        ///
        ///Yantara City
        ///
        ///Tur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_de {
            get {
                return ResourceManager.GetString("text_xy_00000_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------
        ///
        ///Mystery Zone
        ///
        ///Faraway Place
        ///
        ///Vaniville Town
        ///
        ///Route 1
        ///Vaniville Pathway
        ///Aquacorde Town
        ///
        ///Route 2
        ///Avance Trail
        ///Santalune Forest
        ///
        ///Route 3
        ///Ouvert Way
        ///Santalune City
        ///
        ///Route 4
        ///Parterre Way
        ///Lumiose City
        ///
        ///Prism Tower
        ///
        ///Lysandre Labs
        ///
        ///Route 5
        ///Versant Road
        ///Camphrier Town
        ///
        ///Shabboneau Castle
        ///
        ///Route 6
        ///Palais Lane
        ///Parfum Palace
        ///
        ///Route 7
        ///Rivière Walk
        ///Cyllage City
        ///
        ///Route 8
        ///Muraille Coast
        ///Ambrette Town
        ///
        ///Route 9
        ///Spikes Passage
        ///Battle Chateau
        ///
        ///Route 10
        ///Menhir Trail
        ///Geosenge Town
        ///
        ///Route 11
        ///Miroir Way
        ///Reflection Cave
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_en {
            get {
                return ResourceManager.GetString("text_xy_00000_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －
        ///
        ///Lugar misterioso
        ///
        ///Lugar lejano
        ///
        ///Pueblo Boceto
        ///
        ///Ruta 1
        ///Sendero Boceto
        ///Pueblo Acuarela
        ///
        ///Ruta 2
        ///Vía del Avance
        ///Bosque de Novarte
        ///
        ///Ruta 3
        ///Senda Despejada
        ///Ciudad Novarte
        ///
        ///Ruta 4
        ///Senda del Parterre
        ///Ciudad Luminalia
        ///
        ///Torre Prisma
        ///
        ///Laboratorios Lysson
        ///
        ///Ruta 5
        ///Vía Repecho
        ///Pueblo Vánitas
        ///
        ///Castillo Caduco
        ///
        ///Ruta 6
        ///Alameda del Palacio
        ///Palacio Cénit
        ///
        ///Ruta 7
        ///Paseo de la Ribera
        ///Ciudad Relieve
        ///
        ///Ruta 8
        ///Muralla Costera
        ///Pueblo Petroglifo
        ///
        ///Ruta 9
        ///Paso de Rhyhorn
        ///Bastión Batalla
        ///
        ///Ruta 10
        ///Camino Menhires
        ///Pueblo Crómlech
        ///
        ///Ruta  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_es {
            get {
                return ResourceManager.GetString("text_xy_00000_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///Endroit Mystérieux
        ///
        ///Endroit lointain
        ///
        ///Bourg Croquis
        ///
        ///Route 1
        ///Sentier Croquis
        ///Quarellis
        ///
        ///Route 2
        ///Chemin Progrès
        ///Forêt de Neuvartault
        ///
        ///Route 3
        ///Chemin Ouvert
        ///Neuvartault
        ///
        ///Route 4
        ///Route Fleurie
        ///Illumis
        ///
        ///Tour Prismatique
        ///
        ///Labos Lysandre
        ///
        ///Route 5
        ///Chemin du Versant
        ///Fort-Vanitas
        ///
        ///Fort de Vanitas
        ///
        ///Route 6
        ///Allée du Palais
        ///Palais Chaydeuvre
        ///
        ///Route 7
        ///Chemin des Berges
        ///Relifac-le-Haut
        ///
        ///Route 8
        ///Falaise Muraille
        ///Roche-sur-Gliffe
        ///
        ///Route 9
        ///Piste Piquante
        ///Château de Combat
        ///
        ///Route 10
        ///Route Menhir
        ///Cromlac’h
        ///
        ///Route  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_fr {
            get {
                return ResourceManager.GetString("text_xy_00000_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------
        ///
        ///Zona Misteriosa
        ///
        ///Luogo Remoto
        ///
        ///Borgo Bozzetto
        ///
        ///Percorso 1
        ///Vicolo Bozzetto
        ///Rio Acquerello
        ///
        ///Percorso 2
        ///Via Progresso
        ///Bosco Novartopoli
        ///
        ///Percorso 3
        ///Via Aperta
        ///Novartopoli
        ///
        ///Percorso 4
        ///Viale Parterre
        ///Luminopoli
        ///
        ///Torre Prisma
        ///
        ///Laboratori Elisio
        ///
        ///Percorso 5
        ///Via Versante
        ///Castel Vanità
        ///
        ///Maniero Sottotono
        ///
        ///Percorso 6
        ///Boulevard Palazzo
        ///Reggia Aurea
        ///
        ///Percorso 7
        ///Via Fiume
        ///Altoripoli
        ///
        ///Percorso 8
        ///Muraglia Costiera
        ///Petroglifari
        ///
        ///Percorso 9
        ///Sentiero Punzoni
        ///Castello Lotta
        ///
        ///Percorso 10
        ///Strada dei Menhir
        ///Cromlebur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_it {
            get {
                return ResourceManager.GetString("text_xy_00000_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///なぞのばしょ
        ///
        ///とおいばしょ
        ///
        ///アサメタウン
        ///
        ///１ばんどうろ
        ///アサメのこみち
        ///メイスイタウン
        ///
        ///２ばんどうろ
        ///アバンセどおり
        ///ハクダンのもり
        ///
        ///３ばんどうろ
        ///ウベールどおり
        ///ハクダンシティ
        ///
        ///４ばんどうろ
        ///パルテールかいどう
        ///ミアレシティ
        ///
        ///プリズムタワー
        ///
        ///フラダリラボ
        ///
        ///５ばんどうろ
        ///ベルサンどおり
        ///コボクタウン
        ///
        ///ショボンヌじょう
        ///
        ///６ばんどうろ
        ///パレのなみきみち
        ///パルファムきゅうでん
        ///
        ///７ばんどうろ
        ///リビエールライン
        ///ショウヨウシティ
        ///
        ///８ばんどうろ
        ///ミュライユかいがん
        ///コウジンタウン
        ///
        ///９ばんどうろ
        ///トゲトゲさんどう
        ///バトルシャトー
        ///
        ///１０ばんどうろ
        ///メンヒルロード
        ///セキタイタウン
        ///
        ///１１ばんどうろ
        ///ミロワールどおり
        ///うつしみのどうくつ
        ///
        ///シャラシティ
        ///
        ///マスタータワー
        ///
        ///１２ばんどうろ
        ///フラージュどおり
        ///ヒヨクシティ
        ///
        ///１３ばんどうろ
        ///ミアレのこうや
        ///１４ばんどうろ
        ///クノエのりんどう
        ///クノエシティ
        ///
        ///ボールこうじょう
        ///
        ///１５ばんどうろ
        ///ブランどおり
        ///フウジョタウン
        ///
        ///１６ばんどうろ
        ///トリストどおり
        ///\x10\x02뷿P
        ///\x10\x02뷿Q
        ///フロストケイブ
        ///
        ///１７ばんどうろ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_ja {
            get {
                return ResourceManager.GetString("text_xy_00000_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///수수께끼의 장소
        ///
        ///먼 곳
        ///
        ///조아마을
        ///
        ///1번도로
        ///조아의 작은 길
        ///수미마을
        ///
        ///2번도로
        ///아방쎄 도로
        ///백단숲
        ///
        ///3번도로
        ///우베르 도로
        ///백단시티
        ///
        ///4번도로
        ///파르테르 가도
        ///미르시티
        ///
        ///프리즘타워
        ///
        ///플라드리 래버러토리
        ///
        ///5번도로
        ///베르성 도로
        ///고목내마을
        ///
        ///침울한 성
        ///
        ///6번도로
        ///팔레 가로수 길
        ///파르팽 궁전
        ///
        ///7번도로
        ///리비에르 라인
        ///삼채시티
        ///
        ///8번도로
        ///미라유 해안
        ///가라마을
        ///
        ///9번도로
        ///뿔 산길
        ///배틀샤토
        ///
        ///10번도로
        ///멘히르로드
        ///옥유마을
        ///
        ///11번도로
        ///미르와르 도로
        ///비춤의 동굴
        ///
        ///사라시티
        ///
        ///마스터타워
        ///
        ///12번도로
        ///프라주 도로
        ///비익시티
        ///
        ///13번도로
        ///미르 황야
        ///14번도로
        ///후늬 임도
        ///후늬시티
        ///
        ///볼 공장
        ///
        ///15번도로
        ///브렁 도로
        ///버들비마을
        ///
        ///16번도로
        ///트리스트 도로
        ///\x10\x02뷿P
        ///\x10\x02뷿Q
        ///프로스트케이브
        ///
        ///17번도로
        ///맘모꾸리로드
        ///향전시티
        ///
        ///18번도로
        ///에뜨르와 발레 도로
        ///배롱마을
        ///
        ///19번도로
        ///라주 발레 도로
        ///이설시티
        ///
        ///20번도로
        ///미혹의 숲
        ///포켓몬마을
        ///
        ///21번도로
        ///데르니에 도로
        ///22번도로
        ///데뚜르네 도로
        ///챔피언 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_xy_00000_ko {
            get {
                return ResourceManager.GetString("text_xy_00000_ko", resourceCulture);
            }
        }
    }
}
